import type { ChartType } from "../../../types/chartConfigs";

type PropertyType =
    | "string"
    | "number"
    | "boolean"
    | "color"
    | "enum"
    | "range"
    | "array"
    | "object"
    | "field";

interface PropertyMetadata {
    key: string;
    label: string;
    type: PropertyType;
    default: unknown;
    description: string;
    group: string;
    min?: number;
    max?: number;
    step?: number;
    options?: { value: string; label: string }[];
    fieldType?: "numeric" | "categorical" | "date" | "any";
    condition?: (config: Record<string, unknown>) => boolean;
    affectsAggregation?: boolean;
    affectsMultiSeries?: boolean;
}

const orientationOptions = [
    { value: "vertical", label: "Vertical" },
    { value: "horizontal", label: "Horizontal" },
];

const aggregationOptions = [
    { value: "sum", label: "Sum" },
    { value: "avg", label: "Average" },
    { value: "count", label: "Count" },
    { value: "min", label: "Minimum" },
    { value: "max", label: "Maximum" },
    { value: "median", label: "Median" },
];

const sortOrderOptions = [
    { value: "asc", label: "Ascending" },
    { value: "desc", label: "Descending" },
    { value: "none", label: "None" },
];

const sortByOptions = [
    { value: "x", label: "X Axis" },
    { value: "y", label: "Y Axis" },
    { value: "none", label: "None" },
];

const curveTypeOptions = [
    { value: "linear", label: "Linear" },
    { value: "monotone", label: "Smooth (Monotone)" },
    { value: "step", label: "Step" },
    { value: "stepAfter", label: "Step After" },
    { value: "stepBefore", label: "Step Before" },
    { value: "smooth", label: "Smooth" },
];

const strokeStyleOptions = [
    { value: "solid", label: "Solid" },
    { value: "dashed", label: "Dashed" },
    { value: "dotted", label: "Dotted" },
];

const markerShapeOptions = [
    { value: "circle", label: "Circle" },
    { value: "square", label: "Square" },
    { value: "triangle", label: "Triangle" },
    { value: "diamond", label: "Diamond" },
    { value: "cross", label: "Cross" },
    { value: "star", label: "Star" },
];

const labelPositionOptions = [
    { value: "inside", label: "Inside" },
    { value: "outside", label: "Outside" },
    { value: "center", label: "Center" },
];

const legendPositionOptions = [
    { value: "top", label: "Top" },
    { value: "bottom", label: "Bottom" },
    { value: "left", label: "Left" },
    { value: "right", label: "Right" },
    { value: "none", label: "Hidden" },
];

const gridLineStyleOptions = [
    { value: "solid", label: "Solid" },
    { value: "dashed", label: "Dashed" },
    { value: "dotted", label: "Dotted" },
];

const sampleMethodOptions = [
    { value: "random", label: "Random" },
    { value: "stratified", label: "Stratified" },
    { value: "systematic", label: "Systematic" },
];

const trendLineOptions = [
    { value: "none", label: "None" },
    { value: "linear", label: "Linear" },
    { value: "polynomial", label: "Polynomial" },
    { value: "exponential", label: "Exponential" },
    { value: "logarithmic", label: "Logarithmic" },
    { value: "loess", label: "LOESS" },
];

const stackOffsetOptions = [
    { value: "none", label: "None" },
    { value: "expand", label: "Expand (100%)" },
    { value: "silhouette", label: "Silhouette" },
    { value: "wiggle", label: "Wiggle (Streamgraph)" },
];

const valueLabelPositionOptions = [
    { value: "top", label: "Top" },
    { value: "center", label: "Center" },
    { value: "bottom", label: "Bottom" },
];

const commonDataProperties: PropertyMetadata[] = [
    {
        key: "dataFieldX",
        label: "X Axis Field",
        type: "field",
        default: null,
        description: "Field to map on the X axis. Accepts categorical or numeric fields.",
        group: "Data",
        fieldType: "any",
    },
    {
        key: "dataFieldY",
        label: "Y Axis Field",
        type: "field",
        default: null,
        description: "Field to map on the Y axis. Typically a numeric measure.",
        group: "Data",
        fieldType: "numeric",
    },
    {
        key: "aggregation",
        label: "Aggregation",
        type: "enum",
        default: "sum",
        description: "Aggregation function applied to Y values. SUM for totals, AVG for averages.",
        group: "Data",
        options: aggregationOptions,
        affectsAggregation: true,
    },
];

const commonStyleProperties: PropertyMetadata[] = [
    {
        key: "title",
        label: "Chart Title",
        type: "string",
        default: "",
        description: "Display title shown above the chart.",
        group: "Title",
    },
    {
        key: "titleFontSize",
        label: "Title Font Size",
        type: "number",
        default: 14,
        description: "Font size of the chart title in pixels.",
        group: "Title",
        min: 10,
        max: 24,
        step: 1,
    },
    {
        key: "titleFontFamily",
        label: "Title Font Family",
        type: "string",
        default: '"Inter", "Segoe UI", system-ui, sans-serif',
        description: "Font family for the chart title.",
        group: "Title",
    },
    {
        key: "titleFontColor",
        label: "Title Color",
        type: "color",
        default: "#262626",
        description: "Text color for the chart title.",
        group: "Title",
    },
    {
        key: "colorScheme",
        label: "Color Scheme",
        type: "array",
        default: [],
        description: "Array of colors used for data series. Applied in order.",
        group: "Colors",
    },
    {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        default: "#FFFFFF",
        description: "Chart background color.",
        group: "Colors",
    },
    {
        key: "animationDuration",
        label: "Animation Duration",
        type: "number",
        default: 300,
        description: "Duration of chart animations in milliseconds.",
        group: "Animation",
        min: 0,
        max: 2000,
        step: 50,
    },
    {
        key: "maxPoints",
        label: "Max Data Points",
        type: "number",
        default: 500,
        description: "Maximum number of data points to display. Data beyond this is aggregated or sampled.",
        group: "Performance",
        min: 10,
        max: 10000,
        step: 10,
    },
];

const axisProperties: PropertyMetadata[] = [
    {
        key: "xAxis.title",
        label: "X Axis Title",
        type: "string",
        default: "",
        description: "Title text displayed along the X axis.",
        group: "X Axis",
    },
    {
        key: "xAxis.titleFontSize",
        label: "X Axis Title Size",
        type: "number",
        default: 12,
        description: "Font size for the X axis title.",
        group: "X Axis",
        min: 8,
        max: 18,
        step: 1,
    },
    {
        key: "xAxis.labelFontSize",
        label: "X Axis Label Size",
        type: "number",
        default: 11,
        description: "Font size for X axis tick labels.",
        group: "X Axis",
        min: 8,
        max: 14,
        step: 1,
    },
    {
        key: "xAxis.labelRotation",
        label: "X Label Rotation",
        type: "number",
        default: -45,
        description: "Rotation angle for X axis labels in degrees. Negative rotates clockwise.",
        group: "X Axis",
        min: -90,
        max: 90,
        step: 15,
    },
    {
        key: "xAxis.showGridLines",
        label: "X Grid Lines",
        type: "boolean",
        default: true,
        description: "Show vertical grid lines from X axis.",
        group: "X Axis",
    },
    {
        key: "xAxis.gridLineStyle",
        label: "X Grid Style",
        type: "enum",
        default: "dashed",
        description: "Style of vertical grid lines.",
        group: "X Axis",
        options: gridLineStyleOptions,
    },
    {
        key: "yAxis.title",
        label: "Y Axis Title",
        type: "string",
        default: "",
        description: "Title text displayed along the Y axis.",
        group: "Y Axis",
    },
    {
        key: "yAxis.titleFontSize",
        label: "Y Axis Title Size",
        type: "number",
        default: 12,
        description: "Font size for the Y axis title.",
        group: "Y Axis",
        min: 8,
        max: 18,
        step: 1,
    },
    {
        key: "yAxis.labelFontSize",
        label: "Y Axis Label Size",
        type: "number",
        default: 11,
        description: "Font size for Y axis tick labels.",
        group: "Y Axis",
        min: 8,
        max: 14,
        step: 1,
    },
    {
        key: "yAxis.showGridLines",
        label: "Y Grid Lines",
        type: "boolean",
        default: true,
        description: "Show horizontal grid lines from Y axis.",
        group: "Y Axis",
    },
    {
        key: "yAxis.gridLineStyle",
        label: "Y Grid Style",
        type: "enum",
        default: "dashed",
        description: "Style of horizontal grid lines.",
        group: "Y Axis",
        options: gridLineStyleOptions,
    },
    {
        key: "yAxis.min",
        label: "Y Min Value",
        type: "string",
        default: "auto",
        description: "Minimum value for Y axis. Use 'auto' for automatic scaling.",
        group: "Y Axis",
    },
    {
        key: "yAxis.max",
        label: "Y Max Value",
        type: "string",
        default: "auto",
        description: "Maximum value for Y axis. Use 'auto' for automatic scaling.",
        group: "Y Axis",
    },
];

const tooltipProperties: PropertyMetadata[] = [
    {
        key: "tooltip.enabled",
        label: "Show Tooltip",
        type: "boolean",
        default: true,
        description: "Enable interactive tooltips on hover.",
        group: "Tooltip",
    },
    {
        key: "tooltip.format",
        label: "Tooltip Format",
        type: "string",
        default: "{value}",
        description: "Format string for tooltip values. Use {value}, {name}, {percent}.",
        group: "Tooltip",
    },
    {
        key: "tooltip.showSeriesName",
        label: "Show Series Name",
        type: "boolean",
        default: true,
        description: "Display series name in tooltip.",
        group: "Tooltip",
    },
    {
        key: "tooltip.showPercentage",
        label: "Show Percentage",
        type: "boolean",
        default: false,
        description: "Display percentage value in tooltip.",
        group: "Tooltip",
    },
    {
        key: "tooltip.backgroundColor",
        label: "Tooltip Background",
        type: "color",
        default: "#FAFAFA",
        description: "Background color of the tooltip.",
        group: "Tooltip",
    },
];

const legendProperties: PropertyMetadata[] = [
    {
        key: "legend.show",
        label: "Show Legend",
        type: "boolean",
        default: true,
        description: "Display chart legend.",
        group: "Legend",
    },
    {
        key: "legend.position",
        label: "Legend Position",
        type: "enum",
        default: "bottom",
        description: "Position of the legend relative to the chart.",
        group: "Legend",
        options: legendPositionOptions,
    },
    {
        key: "legend.fontSize",
        label: "Legend Font Size",
        type: "number",
        default: 11,
        description: "Font size for legend text.",
        group: "Legend",
        min: 8,
        max: 14,
        step: 1,
    },
    {
        key: "legend.itemSpacing",
        label: "Item Spacing",
        type: "number",
        default: 16,
        description: "Spacing between legend items in pixels.",
        group: "Legend",
        min: 4,
        max: 32,
        step: 2,
    },
];

export const barChartProperties: PropertyMetadata[] = [
    ...commonDataProperties,
    {
        key: "orientation",
        label: "Orientation",
        type: "enum",
        default: "vertical",
        description: "Bar orientation. Vertical for column chart, horizontal for bar chart.",
        group: "Layout",
        options: orientationOptions,
    },
    {
        key: "stacked",
        label: "Stacked",
        type: "boolean",
        default: false,
        description: "Stack bars on top of each other for multi-series data.",
        group: "Layout",
        affectsMultiSeries: true,
    },
    {
        key: "grouped",
        label: "Grouped",
        type: "boolean",
        default: false,
        description: "Group bars side by side for multi-series data.",
        group: "Layout",
        affectsMultiSeries: true,
        condition: (config) => !config.stacked,
    },
    {
        key: "barWidth",
        label: "Bar Width",
        type: "string",
        default: "auto",
        description: "Width of bars. Use 'auto' for automatic sizing or a number in pixels.",
        group: "Bars",
    },
    {
        key: "maxBarWidth",
        label: "Max Bar Width",
        type: "number",
        default: 48,
        description: "Maximum width of bars in pixels when using auto width.",
        group: "Bars",
        min: 8,
        max: 100,
        step: 4,
    },
    {
        key: "barSpacing",
        label: "Bar Spacing",
        type: "number",
        default: 4,
        description: "Spacing between bars within a group in pixels.",
        group: "Bars",
        min: 0,
        max: 20,
        step: 1,
    },
    {
        key: "barCategoryGap",
        label: "Category Gap",
        type: "number",
        default: 16,
        description: "Gap between bar categories in pixels.",
        group: "Bars",
        min: 0,
        max: 40,
        step: 2,
    },
    {
        key: "barRadius",
        label: "Bar Corner Radius",
        type: "array",
        default: [2, 2, 0, 0],
        description: "Corner radius for bars [topLeft, topRight, bottomRight, bottomLeft].",
        group: "Bars",
    },
    {
        key: "sortBy",
        label: "Sort By",
        type: "enum",
        default: "none",
        description: "Field to sort bars by.",
        group: "Sorting",
        options: sortByOptions,
    },
    {
        key: "sortOrder",
        label: "Sort Order",
        type: "enum",
        default: "none",
        description: "Sort direction for bars.",
        group: "Sorting",
        options: sortOrderOptions,
    },
    {
        key: "showValueLabels",
        label: "Value Labels",
        type: "boolean",
        default: false,
        description: "Display value labels on bars.",
        group: "Labels",
    },
    {
        key: "valueLabelPosition",
        label: "Label Position",
        type: "enum",
        default: "top",
        description: "Position of value labels relative to bars.",
        group: "Labels",
        options: valueLabelPositionOptions,
        condition: (config) => config.showValueLabels === true,
    },
    {
        key: "valueLabelFontSize",
        label: "Label Font Size",
        type: "number",
        default: 10,
        description: "Font size for value labels.",
        group: "Labels",
        min: 8,
        max: 14,
        step: 1,
        condition: (config) => config.showValueLabels === true,
    },
    {
        key: "valueLabelFontColor",
        label: "Label Color",
        type: "color",
        default: "#525252",
        description: "Text color for value labels.",
        group: "Labels",
        condition: (config) => config.showValueLabels === true,
    },
    {
        key: "highlightOnHover",
        label: "Highlight on Hover",
        type: "boolean",
        default: true,
        description: "Highlight bars on mouse hover.",
        group: "Interaction",
    },
    {
        key: "selectedBarIndex",
        label: "Selected Bar Index",
        type: "number",
        default: null,
        description: "Index of the programmatically selected bar.",
        group: "Interaction",
    },
    {
        key: "selectedCategory",
        label: "Selected Category",
        type: "string",
        default: null,
        description: "Category name of the selected bar for highlighting.",
        group: "Interaction",
    },
    ...axisProperties,
    ...tooltipProperties,
    ...legendProperties,
    ...commonStyleProperties,
];

export const lineChartProperties: PropertyMetadata[] = [
    ...commonDataProperties,
    {
        key: "curveType",
        label: "Curve Type",
        type: "enum",
        default: "monotone",
        description: "Interpolation method for connecting data points.",
        group: "Line Style",
        options: curveTypeOptions,
    },
    {
        key: "strokeWidth",
        label: "Line Width",
        type: "number",
        default: 2,
        description: "Width of the line stroke in pixels.",
        group: "Line Style",
        min: 1,
        max: 6,
        step: 0.5,
    },
    {
        key: "strokeStyle",
        label: "Line Style",
        type: "enum",
        default: "solid",
        description: "Style of the line stroke.",
        group: "Line Style",
        options: strokeStyleOptions,
    },
    {
        key: "showMarkers",
        label: "Show Markers",
        type: "boolean",
        default: true,
        description: "Display data point markers on the line.",
        group: "Markers",
    },
    {
        key: "markerShape",
        label: "Marker Shape",
        type: "enum",
        default: "circle",
        description: "Shape of data point markers.",
        group: "Markers",
        options: markerShapeOptions,
        condition: (config) => config.showMarkers === true,
    },
    {
        key: "markerSize",
        label: "Marker Size",
        type: "number",
        default: 4,
        description: "Size of data point markers in pixels.",
        group: "Markers",
        min: 2,
        max: 12,
        step: 1,
        condition: (config) => config.showMarkers === true,
    },
    {
        key: "markerFill",
        label: "Fill Markers",
        type: "boolean",
        default: true,
        description: "Fill markers with solid color vs outline only.",
        group: "Markers",
        condition: (config) => config.showMarkers === true,
    },
    {
        key: "sortBy",
        label: "Sort By",
        type: "enum",
        default: "x",
        description: "Field to sort data points by. Usually X for time series.",
        group: "Sorting",
        options: sortByOptions,
    },
    {
        key: "sortOrder",
        label: "Sort Order",
        type: "enum",
        default: "asc",
        description: "Sort direction for data points.",
        group: "Sorting",
        options: sortOrderOptions,
    },
    {
        key: "multiSeries",
        label: "Multi-Series",
        type: "boolean",
        default: false,
        description: "Enable multiple Y measures on the same chart.",
        group: "Series",
        affectsMultiSeries: true,
    },
    {
        key: "seriesFields",
        label: "Series Fields",
        type: "array",
        default: [],
        description: "Array of field names for multiple series.",
        group: "Series",
        condition: (config) => config.multiSeries === true,
    },
    {
        key: "areaFill",
        label: "Area Fill",
        type: "boolean",
        default: false,
        description: "Fill area under the line.",
        group: "Area",
    },
    {
        key: "areaFillOpacity",
        label: "Fill Opacity",
        type: "range",
        default: 0.1,
        description: "Opacity of the area fill (0-1).",
        group: "Area",
        min: 0,
        max: 1,
        step: 0.05,
        condition: (config) => config.areaFill === true,
    },
    {
        key: "areaGradient",
        label: "Gradient Fill",
        type: "boolean",
        default: true,
        description: "Apply gradient to area fill.",
        group: "Area",
        condition: (config) => config.areaFill === true,
    },
    {
        key: "connectNulls",
        label: "Connect Nulls",
        type: "boolean",
        default: false,
        description: "Connect line across null/missing values.",
        group: "Data Handling",
    },
    {
        key: "showMinMax",
        label: "Show Min/Max",
        type: "boolean",
        default: false,
        description: "Highlight minimum and maximum values.",
        group: "Data Handling",
    },
    {
        key: "zoomable",
        label: "Enable Zoom",
        type: "boolean",
        default: false,
        description: "Allow zooming into chart regions.",
        group: "Interaction",
    },
    {
        key: "pannable",
        label: "Enable Pan",
        type: "boolean",
        default: false,
        description: "Allow panning when zoomed.",
        group: "Interaction",
        condition: (config) => config.zoomable === true,
    },
    ...axisProperties,
    ...tooltipProperties,
    ...legendProperties,
    ...commonStyleProperties,
];

export const areaChartProperties: PropertyMetadata[] = [
    ...commonDataProperties,
    {
        key: "curveType",
        label: "Curve Type",
        type: "enum",
        default: "monotone",
        description: "Interpolation method for the area boundary.",
        group: "Shape",
        options: curveTypeOptions,
    },
    {
        key: "strokeWidth",
        label: "Border Width",
        type: "number",
        default: 2,
        description: "Width of the area border line.",
        group: "Border",
        min: 0,
        max: 4,
        step: 0.5,
    },
    {
        key: "showLineBorder",
        label: "Show Border",
        type: "boolean",
        default: true,
        description: "Display border line around the area.",
        group: "Border",
    },
    {
        key: "showMarkers",
        label: "Show Markers",
        type: "boolean",
        default: false,
        description: "Display data point markers on the area boundary.",
        group: "Markers",
    },
    {
        key: "markerShape",
        label: "Marker Shape",
        type: "enum",
        default: "circle",
        description: "Shape of data point markers.",
        group: "Markers",
        options: markerShapeOptions,
        condition: (config) => config.showMarkers === true,
    },
    {
        key: "markerSize",
        label: "Marker Size",
        type: "number",
        default: 4,
        description: "Size of markers in pixels.",
        group: "Markers",
        min: 2,
        max: 12,
        step: 1,
        condition: (config) => config.showMarkers === true,
    },
    {
        key: "stacked",
        label: "Stacked Areas",
        type: "boolean",
        default: false,
        description: "Stack multiple areas on top of each other.",
        group: "Stacking",
        affectsMultiSeries: true,
    },
    {
        key: "stackOffset",
        label: "Stack Offset",
        type: "enum",
        default: "none",
        description: "Stacking method. Expand normalizes to 100%.",
        group: "Stacking",
        options: stackOffsetOptions,
        condition: (config) => config.stacked === true,
    },
    {
        key: "fillOpacity",
        label: "Fill Opacity",
        type: "range",
        default: 0.6,
        description: "Opacity of the area fill (0-1).",
        group: "Fill",
        min: 0,
        max: 1,
        step: 0.05,
    },
    {
        key: "gradientFill",
        label: "Gradient Fill",
        type: "boolean",
        default: true,
        description: "Apply vertical gradient to area fill.",
        group: "Fill",
    },
    {
        key: "baselineValue",
        label: "Baseline Value",
        type: "number",
        default: 0,
        description: "Y value where the area starts. Default is 0.",
        group: "Fill",
    },
    {
        key: "sortBy",
        label: "Sort By",
        type: "enum",
        default: "x",
        description: "Field to sort data points by.",
        group: "Sorting",
        options: sortByOptions,
    },
    {
        key: "sortOrder",
        label: "Sort Order",
        type: "enum",
        default: "asc",
        description: "Sort direction for data points.",
        group: "Sorting",
        options: sortOrderOptions,
    },
    {
        key: "multiSeries",
        label: "Multi-Series",
        type: "boolean",
        default: false,
        description: "Enable multiple areas on the same chart.",
        group: "Series",
        affectsMultiSeries: true,
    },
    {
        key: "seriesFields",
        label: "Series Fields",
        type: "array",
        default: [],
        description: "Array of field names for multiple series.",
        group: "Series",
        condition: (config) => config.multiSeries === true,
    },
    {
        key: "connectNulls",
        label: "Connect Nulls",
        type: "boolean",
        default: false,
        description: "Connect area across null/missing values.",
        group: "Data Handling",
    },
    {
        key: "zoomable",
        label: "Enable Zoom",
        type: "boolean",
        default: false,
        description: "Allow zooming into chart regions.",
        group: "Interaction",
    },
    {
        key: "pannable",
        label: "Enable Pan",
        type: "boolean",
        default: false,
        description: "Allow panning when zoomed.",
        group: "Interaction",
        condition: (config) => config.zoomable === true,
    },
    ...axisProperties,
    ...tooltipProperties,
    ...legendProperties,
    ...commonStyleProperties,
];

export const pieChartProperties: PropertyMetadata[] = [
    {
        key: "dataFieldCategory",
        label: "Category Field",
        type: "field",
        default: null,
        description: "Field containing category names for pie slices.",
        group: "Data",
        fieldType: "categorical",
    },
    {
        key: "dataFieldValue",
        label: "Value Field",
        type: "field",
        default: null,
        description: "Numeric field containing values for each slice.",
        group: "Data",
        fieldType: "numeric",
    },
    {
        key: "aggregation",
        label: "Aggregation",
        type: "enum",
        default: "sum",
        description: "Aggregation function for slice values.",
        group: "Data",
        options: aggregationOptions,
        affectsAggregation: true,
    },
    {
        key: "innerRadius",
        label: "Inner Radius",
        type: "range",
        default: 0,
        description: "Inner radius as ratio (0-1). Set >0 for donut chart.",
        group: "Shape",
        min: 0,
        max: 0.9,
        step: 0.05,
    },
    {
        key: "outerRadius",
        label: "Outer Radius",
        type: "range",
        default: 0.7,
        description: "Outer radius as ratio of container (0-1).",
        group: "Shape",
        min: 0.3,
        max: 1,
        step: 0.05,
    },
    {
        key: "startAngle",
        label: "Start Angle",
        type: "number",
        default: 90,
        description: "Starting angle in degrees. 90 = top, 0 = right.",
        group: "Shape",
        min: -180,
        max: 180,
        step: 15,
    },
    {
        key: "endAngle",
        label: "End Angle",
        type: "number",
        default: -270,
        description: "Ending angle in degrees. -270 for full circle from top.",
        group: "Shape",
        min: -360,
        max: 360,
        step: 15,
    },
    {
        key: "padAngle",
        label: "Slice Spacing",
        type: "number",
        default: 2,
        description: "Gap between slices in degrees.",
        group: "Shape",
        min: 0,
        max: 10,
        step: 0.5,
    },
    {
        key: "cornerRadius",
        label: "Corner Radius",
        type: "number",
        default: 0,
        description: "Corner radius for slice edges in pixels.",
        group: "Shape",
        min: 0,
        max: 20,
        step: 1,
    },
    {
        key: "sortOrder",
        label: "Sort Order",
        type: "enum",
        default: "desc",
        description: "Sort slices by value. Descending shows largest first.",
        group: "Sorting",
        options: sortOrderOptions,
    },
    {
        key: "showLabels",
        label: "Show Labels",
        type: "boolean",
        default: true,
        description: "Display labels on or near pie slices.",
        group: "Labels",
    },
    {
        key: "labelFormat",
        label: "Label Format",
        type: "string",
        default: "{name}: {percent}%",
        description: "Format string for labels. Use {name}, {value}, {percent}.",
        group: "Labels",
        condition: (config) => config.showLabels === true,
    },
    {
        key: "labelPosition",
        label: "Label Position",
        type: "enum",
        default: "outside",
        description: "Position of slice labels.",
        group: "Labels",
        options: labelPositionOptions,
        condition: (config) => config.showLabels === true,
    },
    {
        key: "labelMinAngle",
        label: "Min Label Angle",
        type: "number",
        default: 10,
        description: "Minimum slice angle to show label. Prevents crowding.",
        group: "Labels",
        min: 0,
        max: 30,
        step: 1,
        condition: (config) => config.showLabels === true,
    },
    {
        key: "showLabelLines",
        label: "Show Label Lines",
        type: "boolean",
        default: true,
        description: "Draw lines connecting slices to external labels.",
        group: "Labels",
        condition: (config) => config.showLabels === true && config.labelPosition === "outside",
    },
    {
        key: "labelLineLength",
        label: "Label Line Length",
        type: "number",
        default: 16,
        description: "Length of label connector lines in pixels.",
        group: "Labels",
        min: 8,
        max: 40,
        step: 2,
        condition: (config) => config.showLabels === true && config.showLabelLines === true,
    },
    {
        key: "maxSlices",
        label: "Max Slices",
        type: "number",
        default: 12,
        description: "Maximum number of slices. Excess grouped into 'Other'.",
        group: "Data Handling",
        min: 3,
        max: 24,
        step: 1,
    },
    {
        key: "otherSliceLabel",
        label: "Other Slice Label",
        type: "string",
        default: "Other",
        description: "Label for grouped smaller slices.",
        group: "Data Handling",
    },
    {
        key: "explodeSliceIndex",
        label: "Explode Slice",
        type: "number",
        default: null,
        description: "Index of slice to explode/highlight. Null for none.",
        group: "Interaction",
    },
    {
        key: "explodeOffset",
        label: "Explode Offset",
        type: "number",
        default: 8,
        description: "Distance to offset exploded slice in pixels.",
        group: "Interaction",
        min: 0,
        max: 30,
        step: 2,
    },
    {
        key: "centerLabel",
        label: "Center Label",
        type: "string",
        default: "",
        description: "Text displayed in the center (donut charts only).",
        group: "Donut",
        condition: (config) => (config.innerRadius as number) > 0,
    },
    {
        key: "centerLabelFontSize",
        label: "Center Label Size",
        type: "number",
        default: 14,
        description: "Font size for center label.",
        group: "Donut",
        min: 10,
        max: 24,
        step: 1,
        condition: (config) => (config.innerRadius as number) > 0 && (config.centerLabel as string).length > 0,
    },
    {
        key: "centerLabelFontColor",
        label: "Center Label Color",
        type: "color",
        default: "#404040",
        description: "Color for center label text.",
        group: "Donut",
        condition: (config) => (config.innerRadius as number) > 0 && (config.centerLabel as string).length > 0,
    },
    ...tooltipProperties.map((p) => ({
        ...p,
        default: p.key === "tooltip.showPercentage" ? true : p.default,
    })),
    ...legendProperties.map((p) => ({
        ...p,
        default: p.key === "legend.position" ? "right" : p.default,
    })),
    ...commonStyleProperties,
];

export const scatterChartProperties: PropertyMetadata[] = [
    {
        key: "dataFieldX",
        label: "X Axis Field",
        type: "field",
        default: null,
        description: "Numeric field for X axis position.",
        group: "Data",
        fieldType: "numeric",
    },
    {
        key: "dataFieldY",
        label: "Y Axis Field",
        type: "field",
        default: null,
        description: "Numeric field for Y axis position.",
        group: "Data",
        fieldType: "numeric",
    },
    {
        key: "dataFieldSize",
        label: "Size Field",
        type: "field",
        default: null,
        description: "Optional numeric field to control point size (bubble chart).",
        group: "Data",
        fieldType: "numeric",
    },
    {
        key: "dataFieldColor",
        label: "Color Field",
        type: "field",
        default: null,
        description: "Optional field to control point color by category or value.",
        group: "Data",
        fieldType: "any",
    },
    {
        key: "aggregation",
        label: "Aggregation",
        type: "enum",
        default: "count",
        description: "Aggregation when multiple points overlap.",
        group: "Data",
        options: aggregationOptions,
        affectsAggregation: true,
    },
    {
        key: "pointSize",
        label: "Point Size",
        type: "number",
        default: 6,
        description: "Size of scatter points in pixels.",
        group: "Points",
        min: 2,
        max: 20,
        step: 1,
    },
    {
        key: "minPointSize",
        label: "Min Point Size",
        type: "number",
        default: 4,
        description: "Minimum point size when using size field.",
        group: "Points",
        min: 2,
        max: 12,
        step: 1,
        condition: (config) => config.dataFieldSize !== null,
    },
    {
        key: "maxPointSize",
        label: "Max Point Size",
        type: "number",
        default: 24,
        description: "Maximum point size when using size field.",
        group: "Points",
        min: 12,
        max: 48,
        step: 2,
        condition: (config) => config.dataFieldSize !== null,
    },
    {
        key: "pointShape",
        label: "Point Shape",
        type: "enum",
        default: "circle",
        description: "Shape of scatter points.",
        group: "Points",
        options: markerShapeOptions,
    },
    {
        key: "pointOpacity",
        label: "Point Opacity",
        type: "range",
        default: 0.7,
        description: "Opacity of scatter points (0-1).",
        group: "Points",
        min: 0.1,
        max: 1,
        step: 0.05,
    },
    {
        key: "pointBorderWidth",
        label: "Border Width",
        type: "number",
        default: 1,
        description: "Width of point border in pixels.",
        group: "Points",
        min: 0,
        max: 4,
        step: 0.5,
    },
    {
        key: "pointBorderColor",
        label: "Border Color",
        type: "color",
        default: "transparent",
        description: "Color of point border. Transparent for no border.",
        group: "Points",
    },
    {
        key: "sampleMethod",
        label: "Sample Method",
        type: "enum",
        default: "random",
        description: "Method for sampling large datasets.",
        group: "Sampling",
        options: sampleMethodOptions,
    },
    {
        key: "sampleSize",
        label: "Sample Size",
        type: "number",
        default: 1000,
        description: "Maximum number of points to display.",
        group: "Sampling",
        min: 100,
        max: 10000,
        step: 100,
    },
    {
        key: "jitter",
        label: "Jitter Amount",
        type: "range",
        default: 0,
        description: "Random offset to separate overlapping points (0-1).",
        group: "Sampling",
        min: 0,
        max: 1,
        step: 0.05,
    },
    {
        key: "showTrendLine",
        label: "Show Trend Line",
        type: "boolean",
        default: false,
        description: "Display a trend/regression line through the data.",
        group: "Trend Line",
    },
    {
        key: "trendLineType",
        label: "Trend Line Type",
        type: "enum",
        default: "linear",
        description: "Type of trend line to fit.",
        group: "Trend Line",
        options: trendLineOptions,
        condition: (config) => config.showTrendLine === true,
    },
    {
        key: "trendLineColor",
        label: "Trend Line Color",
        type: "color",
        default: "#A3A3A3",
        description: "Color of the trend line.",
        group: "Trend Line",
        condition: (config) => config.showTrendLine === true,
    },
    {
        key: "trendLineWidth",
        label: "Trend Line Width",
        type: "number",
        default: 1.5,
        description: "Width of trend line in pixels.",
        group: "Trend Line",
        min: 0.5,
        max: 4,
        step: 0.5,
        condition: (config) => config.showTrendLine === true,
    },
    {
        key: "trendLineStyle",
        label: "Trend Line Style",
        type: "enum",
        default: "dashed",
        description: "Style of trend line.",
        group: "Trend Line",
        options: strokeStyleOptions,
        condition: (config) => config.showTrendLine === true,
    },
    {
        key: "showConfidenceInterval",
        label: "Confidence Interval",
        type: "boolean",
        default: false,
        description: "Show confidence band around trend line.",
        group: "Trend Line",
        condition: (config) => config.showTrendLine === true,
    },
    {
        key: "confidenceLevel",
        label: "Confidence Level",
        type: "range",
        default: 0.95,
        description: "Confidence level for interval (0.9, 0.95, 0.99).",
        group: "Trend Line",
        min: 0.8,
        max: 0.99,
        step: 0.01,
        condition: (config) => config.showTrendLine === true && config.showConfidenceInterval === true,
    },
    {
        key: "highlightOutliers",
        label: "Highlight Outliers",
        type: "boolean",
        default: false,
        description: "Visually distinguish statistical outliers.",
        group: "Outliers",
    },
    {
        key: "outlierThreshold",
        label: "Outlier Threshold",
        type: "number",
        default: 2,
        description: "Standard deviations to consider as outlier.",
        group: "Outliers",
        min: 1,
        max: 4,
        step: 0.5,
        condition: (config) => config.highlightOutliers === true,
    },
    {
        key: "outlierColor",
        label: "Outlier Color",
        type: "color",
        default: "#DC2626",
        description: "Color for outlier points.",
        group: "Outliers",
        condition: (config) => config.highlightOutliers === true,
    },
    {
        key: "showQuadrants",
        label: "Show Quadrants",
        type: "boolean",
        default: false,
        description: "Divide chart into four quadrants.",
        group: "Quadrants",
    },
    {
        key: "quadrantOriginX",
        label: "Quadrant X Origin",
        type: "string",
        default: "mean",
        description: "X value for quadrant division: number, 'mean', or 'median'.",
        group: "Quadrants",
        condition: (config) => config.showQuadrants === true,
    },
    {
        key: "quadrantOriginY",
        label: "Quadrant Y Origin",
        type: "string",
        default: "mean",
        description: "Y value for quadrant division: number, 'mean', or 'median'.",
        group: "Quadrants",
        condition: (config) => config.showQuadrants === true,
    },
    {
        key: "zoomable",
        label: "Enable Zoom",
        type: "boolean",
        default: true,
        description: "Allow zooming into chart regions.",
        group: "Interaction",
    },
    {
        key: "pannable",
        label: "Enable Pan",
        type: "boolean",
        default: true,
        description: "Allow panning when zoomed.",
        group: "Interaction",
        condition: (config) => config.zoomable === true,
    },
    ...axisProperties,
    ...tooltipProperties,
    ...legendProperties,
    ...commonStyleProperties,
];

export const chartPropertyMap: Record<ChartType, PropertyMetadata[]> = {
    bar: barChartProperties,
    line: lineChartProperties,
    area: areaChartProperties,
    pie: pieChartProperties,
    scatter: scatterChartProperties,
};

export function getPropertiesForChartType(type: ChartType): PropertyMetadata[] {
    return chartPropertyMap[type] || [];
}

export function getPropertyGroups(type: ChartType): string[] {
    const props = getPropertiesForChartType(type);
    const groups = new Set<string>();
    props.forEach((p) => groups.add(p.group));
    return Array.from(groups);
}

export function getPropertiesByGroup(type: ChartType, group: string): PropertyMetadata[] {
    return getPropertiesForChartType(type).filter((p) => p.group === group);
}

export function filterVisibleProperties(
    properties: PropertyMetadata[],
    config: Record<string, unknown>
): PropertyMetadata[] {
    return properties.filter((p) => {
        if (!p.condition) return true;
        return p.condition(config);
    });
}
